version: '3'

services:
  php-mvc:
    image: privatehub/php-mvc/php-mvc
    #build:
      #context: .
      # Add: 
      #   - ./_build:/_build
      #   - ./.installer/.docker/nginx.conf:/etc/nginx/nginx.conf
      #   - ./.installer/.docker/supervisord.conf:/etc/supervisord.conf
    ports:
      - 8082:8082
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: ["supervisord", "-c", "/etc/supervisord.conf", "-n"]
