version: '3.8'

services:
  db:
    build:
      context: ./database
      dockerfile: Containerfile
    container_name: templates-db
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
