version: 3.8
networks:
  test-app-net:
    driver: bridge
services:
  test-app-app:
    build: .
    container_name: test-app-app
    ports:
      0: 8447:8080
    volumes:
      0: ./.installer/test-app:/var/www/.installer/test-app:Z
    depends_on:
      0: test-app-db
    networks:
      0: test-app-net
  test-app-db:
    image: postgres:14
    container_name: test-app-postgres
    environment:
      POSTGRES_DB: test-app_db
      POSTGRES_USER: test-app_user
      POSTGRES_PASSWORD: 70e5d8562672b835fe0840203e2c5f40
    volumes:
      0: ./data/test-app:/var/lib/postgresql/data:Z
      1: ./.installer/test-app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:Z
    networks:
      0: test-app-net
    healthcheck:
      test:
        0: CMD-SHELL
        1: pg_isready -U test-app_user
      interval: 5s
      timeout: 5s
      retries: 5
