---
- name: {{APP_NAME}} Demo Playbook
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Log webhook event
      debug:
        msg: "Received event: {{ event_type }} from {{ source }} for app: {{ app_name }}"
    
    - name: Add demo item via API
      uri:
        url: "{{ api_url }}/items"
        method: POST
        body_format: json
        body:
          name: "EDA Generated Item"
          description: "Created by Ansible EDA at {{ ansible_date_time.iso8601 }}"
        headers:
          Content-Type: "application/json"
      register: create_result
      
    - name: Log creation result
      debug:
        msg: "Item created successfully with ID: {{ create_result.json.id | default('unknown') }}"