<?php

declare(strict_types=1);

namespace App\Controllers;

use Nimbus\Controller\AbstractController;
use App\Models\DemoModel;

/**
 * IndexController - A simple demonstration controller
 * 
 * Demonstrates the Nimbus MVC framework capabilities including:
 * - Database integration with PostgreSQL
 * - RESTful API endpoints
 * - Mustache template rendering
 * - EDA (Event-Driven Ansible) integration
 * - Keycloak SSO integration
 * 
 * @package App\Controllers
 * @author Generated by Nimbus Framework
 * @license Apache-2.0
 * @copyright 2025 SmallCloud, LLC
 */
class IndexController extends AbstractController
{
    /** @var DemoModel|null Database model; null when the app has no database */
    private ?DemoModel $demoModel = null;

    /**
     * Initialize controller dependencies
     *
     * Sets up session management and initializes the demo model
     *
     * @return void
     */
    protected function initialize(): void
    {
        // Ensure session is started
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }

        // Apps created with --no-db (or with the database down) must still
        // render: PDO connects lazily and throws here if unreachable.
        try {
            $this->demoModel = new DemoModel($this->getDb());
        } catch (\Throwable $e) {
            $this->demoModel = null;
        }
    }

    /**
     * Guard for API endpoints that need the database.
     * Responds 503 and returns false when the app has no (reachable) database.
     */
    private function requireDb(): bool
    {
        if ($this->demoModel === null) {
            $this->error('Database not available for this app', 503);
            return false;
        }
        return true;
    }
    
    /**
     * Home page handler
     * 
     * Displays the main demo page with application features,
     * statistics, and integration status for EDA and Keycloak
     * 
     * @return void
     */
    public function index(): void
    {
        $config = $this->getConfig();
        $appSlug = $config['installer-name'] ?? 'app';

        // Feature flags. filter_var(FILTER_VALIDATE_BOOLEAN) accepts real booleans
        // as well as legacy string values ('true'/'false'/'1'/'0') from older
        // generated configs, so a stale app.config.php can never mis-render state.
        $hasEda = filter_var($config['has_eda'] ?? false, FILTER_VALIDATE_BOOLEAN);
        $hasKeycloak = filter_var($config['keycloak']['enabled'] ?? false, FILTER_VALIDATE_BOOLEAN);

        // Live probe, not config: true only if the database actually answers.
        $hasDatabase = $this->demoModel !== null && $this->demoModel->isConnected();

        $features = [
            ['name' => 'MVC Architecture', 'enabled' => true],
            ['name' => 'RESTful API Support', 'enabled' => true],
            [
                'name' => 'Database (PostgreSQL)',
                'enabled' => $hasDatabase,
                'command' => $hasDatabase ? null : 'composer nimbus:up ' . $appSlug
            ],
            [
                'name' => 'Event-Driven Ansible (EDA)',
                'enabled' => $hasEda,
                'command' => $hasEda ? null : 'composer nimbus:add-eda ' . $appSlug
            ],
            [
                'name' => 'Keycloak SSO Integration',
                'enabled' => $hasKeycloak,
                'command' => $hasKeycloak ? null : 'composer nimbus:add-keycloak ' . $appSlug
            ]
        ];
        
        // Keycloak details from app.config.php. (app.nimbus.json is NOT
        // installed into app/ — only the assets map is — so read the config
        // array, which carries the host-published ports.)
        $keycloakAdminPassword = '';
        $keycloakRealm = $config['keycloak']['realm'] ?: $appSlug . '-realm';
        $keycloakPort = $config['keycloak']['host_port'] ?? 8080;
        
        $data = [
            'title' => $config['app_name'] ?? 'Nimbus Demo',
            'message' => 'Welcome to your Nimbus application!',
            'features' => $features,
            'stats' => $this->demoModel !== null
                ? $this->demoModel->getStats()
                : ['total_items' => 0, 'last_updated' => 'Never'],
            'has_eda' => $hasEda,
            'eda_port' => $config['eda_port'] ?? 5000,
            'has_keycloak' => $hasKeycloak,
            'has_database' => $hasDatabase,
            'enable_keycloak_command' => 'composer nimbus:add-keycloak ' . $appSlug,
            'user' => $_SESSION['user'] ?? null,
            'app_name' => $appSlug,
            // Lowercase on purpose: uppercase {{ }} tokens are create-time
            // scaffolding placeholders, and naming runtime view data like one
            // risks it being substituted at create (see TODO-PLACEHOLDERS.md).
            'keycloak_admin_password' => $keycloakAdminPassword,
            'keycloak_realm' => $keycloakRealm,
            'keycloak_port' => $keycloakPort
        ];
        
        $html = $this->render('demo/index', $data);
        echo $html;
    }
    
    /**
     * API endpoint - Get all items
     * 
     * Returns a JSON response with all demo items from the database
     * 
     * @return void
     */
    public function apiList(): void
    {
        if (!$this->requireDb()) {
            return;
        }
        try {
            $items = $this->demoModel->getAllItems();
            $this->json([
                'success' => true,
                'data' => $items,
                'count' => count($items)
            ]);
        } catch (\Exception $e) {
            $this->error($e->getMessage(), 500);
        }
    }
    
    /**
     * API endpoint - Get single item
     * 
     * Returns a JSON response with a specific demo item
     * 
     * @param int|string $id The item ID
     * @return void
     */
    public function apiGet($id): void
    {
        if (!$this->requireDb()) {
            return;
        }
        try {
            $item = $this->demoModel->getItem($id);
            if (!$item) {
                $this->error('Item not found', 404);
                return;
            }
            $this->json(['success' => true, 'data' => $item]);
        } catch (\Exception $e) {
            $this->error($e->getMessage(), 500);
        }
    }
    
    /**
     * API endpoint - Create item
     * 
     * Creates a new demo item with the provided data
     * Validates that name and description are provided
     * 
     * @return void
     */
    public function apiCreate(): void
    {
        if (!$this->requireDb()) {
            return;
        }
        $data = $this->getRequestData();
        
        if (!$this->validate($data, ['name', 'description'])) {
            $this->error('Name and description are required');
            return;
        }
        
        try {
            $id = $this->demoModel->createItem($data);
            $this->json([
                'success' => true,
                'message' => 'Item created successfully',
                'id' => $id
            ], 201);
        } catch (\Exception $e) {
            $this->error($e->getMessage(), 500);
        }
    }
    
    /**
     * API endpoint - Update item
     * 
     * Updates an existing demo item with the provided data
     * 
     * @param int|string $id The item ID to update
     * @return void
     */
    public function apiUpdate($id): void
    {
        if (!$this->requireDb()) {
            return;
        }
        $data = $this->getRequestData();
        
        try {
            $updated = $this->demoModel->updateItem($id, $data);
            if (!$updated) {
                $this->error('Item not found', 404);
                return;
            }
            $this->success(null, 'Item updated successfully');
        } catch (\Exception $e) {
            $this->error($e->getMessage(), 500);
        }
    }
    
    /**
     * API endpoint - Delete item
     * 
     * Deletes an existing demo item
     * 
     * @param int|string $id The item ID to delete
     * @return void
     */
    public function apiDelete($id): void
    {
        if (!$this->requireDb()) {
            return;
        }
        try {
            $deleted = $this->demoModel->deleteItem($id);
            if (!$deleted) {
                $this->error('Item not found', 404);
                return;
            }
            $this->success(null, 'Item deleted successfully');
        } catch (\Exception $e) {
            $this->error($e->getMessage(), 500);
        }
    }
    
    /**
     * EDA webhook proxy to avoid CORS issues
     * 
     * Forwards webhook requests to the EDA container if EDA is enabled.
     * This serves as a proxy to avoid CORS issues when calling EDA from browser.
     * 
     * @return void
     */
    public function edaWebhook(): void
    {
        $config = $this->getConfig();
        $hasEda = $config['has_eda'] ?? false;
        
        if (!$hasEda) {
            $this->error('EDA is not enabled for this app', 404);
            return;
        }
        
        $edaPort = $config['eda_port'] ?? 5000;
        $appSlug = $config['installer-name'] ?? 'app';
        $requestData = $this->getRequestData();

        // Forward the request to the EDA container. Container-to-container
        // traffic always targets the EDA server's own internal port (5000),
        // not the host-published $edaPort, which only matters from outside.
        $edaUrl = "http://{$appSlug}-eda:5000/endpoint";
        
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $edaUrl);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'Content-Type: application/json',
        ]);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($requestData));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 10);
        
        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $curlError = curl_error($ch);
        curl_close($ch);
        
        if ($curlError) {
            $this->error('Failed to reach EDA container: ' . $curlError, 502);
            return;
        }
        
        // Return success regardless of EDA response
        $this->json([
            'success' => true,
            'message' => 'Webhook forwarded to EDA',
            'eda_response_code' => $httpCode
        ]);
    }
}
