---
- name: Send certificates via callback
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Send HTTP POST request
      ansible.builtin.uri:
        url: "{{ callback_url }}"
        method: POST
        body: |
          {
            "certificates": {{ certificates | to_json }}
          }
        headers:
          Content-Type: "application/json"
        body_format: json