---
- name: Order SSL certificate with certbot (EDA triggered)
  hosts: localhost
  gather_facts: no

  vars:
    domain: ""
    email: ""
    order_id: ""
    validation_method: "http"
    acme_version: 1
    app_name: "') }}"

  tasks:
    - name: Ensure python3 and pip installed
      ansible.builtin.shell: |
        microdnf install -y python3 python3-pip
      args:
        creates: /usr/bin/pip3

    - name: Install certbot via pip3
      ansible.builtin.shell: |
        pip3 install --upgrade certbot
      args:
        creates: /usr/local/bin/certbot

    - name: Run certbot with http-01 validation (standalone)
      ansible.builtin.command: >
        certbot certonly --standalone
        --non-interactive --agree-tos
        -m 
        -d 
      when: validation_method == "http"
      register: certbot_result
      ignore_errors: yes

    # - name: Run certbot with manual dns-01 challenge
    #   ansible.builtin.command: >
    #     certbot certonly --manual --preferred-challenges dns
    #     --non-interactive --agree-tos
    #     -m 
    #     -d 
    #   when: validation_method == "dns"
    #   register: certbot_result
    #   ignore_errors: yes

    - name: Debug output on success
      debug:
        msg: |
          Certificate issued for  with order ID 
          Certbot output: 
      when: certbot_result is succeeded

    - name: Post failure to order endpoint
      ansible.builtin.uri:
        url: "http://testgenerated-app:8080/lkui/api/orders/{{ order_id }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          status: "ORDER_FAILED"
          error_message: "Certbot failed: {{ certbot_result.stderr | default('Unknown error') }}"
        status_code: [200, 201]
      when: certbot_result is failed

    - name: Post success to order endpoint
      ansible.builtin.uri:
        url: "http://testgenerated-app:8080/lkui/api/orders/{{ order_id }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          status: "ORDER_COMPLETED"
          certificate_path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
        status_code: [200, 201]
      when: certbot_result is succeeded