---
- name: Order SSL certificate with certbot (EDA triggered)
  hosts: localhost
  gather_facts: no

  vars:
    domain: ""
    email: ""
    order_id: ""
    validation_method: "http"
    acme_version: 1

  tasks:
    - name: Ensure python3 and pip installed
      ansible.builtin.shell: |
        microdnf install -y python3 python3-pip
      args:
        creates: /usr/bin/pip3

    - name: Install certbot via pip3
      ansible.builtin.shell: |
        pip3 install --upgrade certbot
      args:
        creates: /usr/local/bin/certbot

    - name: Run certbot with http-01 validation (standalone)
      ansible.builtin.command: >
        certbot certonly --standalone
        --non-interactive --agree-tos
        -m {{ email }}
        -d {{ domain }}
      when: validation_method == "http"
      register: certbot_result
      ignore_errors: yes

    # - name: Run certbot with manual dns-01 challenge
    #   ansible.builtin.command: >
    #     certbot certonly --manual --preferred-challenges dns
    #     --non-interactive --agree-tos
    #     -m {{ email }}
    #     -d {{ domain }}
    #   when: validation_method == "dns"
    #   register: certbot_result
    #   ignore_errors: yes

    - name: Debug output on success
      debug:
        msg: |
          Certificate issued for {{ domain }} with order ID {{ order_id }}
          Certbot output: {{ certbot_result.stdout | default('Certificate issued') }}
      when: (certbot_result | default({})).get('rc', 1) == 0

    - name: Post failure to order endpoint
      ansible.builtin.uri:
        url: "http://lkui-app:8080/lkui/api/orders/{{ order_id }}/certificate"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          status: "ORDER_FAILED"
          error_message: "{{ certbot_result.stderr | default('Unknown certbot error. See /var/log/letsencrypt/letsencrypt.log') }}"
      when: (certbot_result | default({})).get('rc', 1) != 0

    - name: Post success to order endpoint
      ansible.builtin.uri:
        url: "http://lkui-app:8080/lkui/api/orders/{{ order_id }}/certificate"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          status: "ORDER_SUCCESS"
          message: "Certificate issued successfully"
      when: (certbot_result | default({})).get('rc', 1) == 0
