---
- name: Order SSL certificate with Let's Encrypt
  hosts: localhost
  gather_facts: no
  vars:
    acme_account_key: "/etc/letsencrypt/account.key"
    cert_key: "/etc/letsencrypt/.key"
    cert_fullchain: "/etc/letsencrypt/.crt"
    acme_version: ""
  tasks:
    - name: Ensure account key exists
      community.crypto.openssl_privatekey:
        path: ""
        size: 4096
      register: account_key_result

    - name: Ensure domain private key exists
      community.crypto.openssl_privatekey:
        path: ""
        size: 2048
      register: domain_key_result

    - name: Order certificate using DNS challenge
      community.crypto.acme_certificate:
        account_key_src: ""
        csr: ""
        dest: ""
        challenge: dns-01
        acme_directory: https://acme-v02.api.letsencrypt.org/directory
        terms_agreed: yes
        remaining_days: 30
        acme_version: ""
      register: cert_result
      ignore_errors: yes

    - name: Debug output on success
      debug:
        msg: |
          Certificate issued for  with order ID 
          Cert path: 
      when: cert_result is succeeded

    - name: Post failure to order endpoint
      ansible.builtin.uri:
        url: "http://testgenerated-app:8080/lkui/api/orders/"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          status: "ORDER_FAILED"
          error_message: ""
      when: cert_result is failed

    - name: Post certificate to order endpoint
      ansible.builtin.uri:
        url: "http://testgenerated-app:8080/lkui/api/orders//certificate"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          cert_content: "" #fixme
      when: cert_result is succeeded

    - name: Post success to order endpoint
      ansible.builtin.uri:
        url: "http://testgenerated-app:8080/lkui/api/orders/"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          status: "ORDER_COMPLETED"
          order_id: ""
          error_message: "Self-signed certificate generated successfully"
      when: cert_result is succeeded