---
- name: Check Keycloak Health Status
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Check Keycloak health endpoint
      uri:
        url: "{{ keycloak_url }}/health"
        method: GET
        status_code: [200, 503]
        validate_certs: no
      register: health_check

    - name: Send health status to app
      uri:
        url: "{{ callback_url }}"
        method: POST
        headers:
          Content-Type: application/json
        body_format: json
        body:
          status: "{{ 'healthy' if health_check.status == 200 else 'unhealthy' }}"
          details: "{{ health_check.json | default({}) }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
        validate_certs: no
      ignore_errors: yes