---
- name: {{APP_NAME}} API Notification
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:
    - name: Log webhook event
      debug:
        msg: "Received {{ event_type }} event from {{ source }} for app {{ app_name }}"
    
    - name: Add demo item via API
      uri:
        url: "{{ api_url }}/items"
        method: POST
        body_format: json
        body:
          name: "EDA Generated Item"
          description: "Created by Ansible EDA at {{ ansible_date_time.iso8601 }}"
        headers:
          Content-Type: "application/json"
        status_code: 201
      register: create_result
      
    - name: Log creation result
      debug:
        msg: "Item created successfully with ID: {{ create_result.json.id | default('unknown') }}"