<?php

declare(strict_types=1);

namespace App\Models;

use PDO;
use PDOStatement;

/**
 * DemoModel - Simple model for demonstration
 * 
 * Provides CRUD operations for demo_items table
 * Demonstrates database interaction patterns in Nimbus framework
 * 
 * @package App\Models
 * @author Generated by Nimbus Framework
 * @license Apache-2.0
 * @copyright 2025 SmallCloud, LLC
 */
class DemoModel
{
    /** @var PDO Database connection instance */
    private PDO $db;
    
    /**
     * Constructor
     * 
     * @param PDO $db Database connection instance
     */
    public function __construct(PDO $db)
    {
        $this->db = $db;
    }
    
    /**
     * Get statistics about demo items
     * 
     * Returns total count and last updated timestamp
     * 
     * @return array<string, int|string> Statistics data
     */
    public function getStats(): array
    {
        try {
            $stmt = $this->db->query("SELECT COUNT(*) as total FROM demo_items");
            $total = $stmt->fetchColumn();
            
            return [
                'total_items' => $total,
                'last_updated' => date('Y-m-d H:i:s')
            ];
        } catch (\Exception $e) {
            return [
                'total_items' => 0,
                'last_updated' => 'Never'
            ];
        }
    }
    
    /**
     * Get all items from the database
     * 
     * Returns all demo items ordered by creation date (newest first)
     * 
     * @return array<int, array<string, mixed>> Array of demo items
     */
    public function getAllItems(): array
    {
        $stmt = $this->db->query("
            SELECT * FROM demo_items 
            ORDER BY created_at DESC
        ");
        return $stmt->fetchAll();
    }
    
    /**
     * Get a single item by ID
     * 
     * @param int $id The item ID to retrieve
     * @return array<string, mixed>|null The item data or null if not found
     */
    public function getItem(int $id): ?array
    {
        $stmt = $this->db->prepare("
            SELECT * FROM demo_items 
            WHERE id = :id
        ");
        $stmt->execute(['id' => $id]);
        $result = $stmt->fetch();
        
        return $result ?: null;
    }
    
    /**
     * Create a new item
     * 
     * @param array<string, mixed> $data Item data (must contain 'name' and 'description')
     * @return int The ID of the newly created item
     */
    public function createItem(array $data): int
    {
        $stmt = $this->db->prepare("
            INSERT INTO demo_items (name, description, created_at) 
            VALUES (:name, :description, NOW())
        ");
        
        $stmt->execute([
            'name' => $data['name'],
            'description' => $data['description']
        ]);
        
        return (int) $this->db->lastInsertId();
    }
    
    /**
     * Update an existing item
     * 
     * @param int $id The item ID to update
     * @param array<string, mixed> $data Updated item data
     * @return bool True if the item was updated, false otherwise
     */
    public function updateItem(int $id, array $data): bool
    {
        $fields = [];
        $params = ['id' => $id];
        
        if (isset($data['name'])) {
            $fields[] = 'name = :name';
            $params['name'] = $data['name'];
        }
        
        if (isset($data['description'])) {
            $fields[] = 'description = :description';
            $params['description'] = $data['description'];
        }
        
        if (empty($fields)) {
            return false;
        }
        
        $fields[] = 'updated_at = NOW()';
        
        $stmt = $this->db->prepare("
            UPDATE demo_items 
            SET " . implode(', ', $fields) . "
            WHERE id = :id
        ");
        
        $stmt->execute($params);
        return $stmt->rowCount() > 0;
    }
    
    /**
     * Delete an item by ID
     * 
     * @param int $id The item ID to delete
     * @return bool True if the item was deleted, false otherwise
     */
    public function deleteItem(int $id): bool
    {
        $stmt = $this->db->prepare("
            DELETE FROM demo_items 
            WHERE id = :id
        ");
        
        $stmt->execute(['id' => $id]);
        return $stmt->rowCount() > 0;
    }
}