version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: lkui-postgres
    environment:
      POSTGRES_USER: lkui
      POSTGRES_PASSWORD: lkui_password
      POSTGRES_DB: lkui
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lkui -d lkui"]
      interval: 5s
      timeout: 5s
      retries: 5
