version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_USER: lkui
      POSTGRES_PASSWORD: lkui_secure_password_2024
      POSTGRES_DB: lkui
    volumes:
      - ./.installer/lkui/database/data:/var/lib/postgresql/data
      - ./.installer/lkui/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init-pg-hba.sh:/docker-entrypoint-initdb.d/02-init-pg-hba.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lkui -d lkui"]
      interval: 5s
      timeout: 5s
      retries: 5