---
- name: {{APP_NAME}} Demo EDA Rules
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        endpoint: /endpoint
  rules:
    - name: Handle add item webhook
      condition: event.payload.event == "add_item"
      action:
        run_playbook:
          name: "/playbooks/api-notification.yml"
          extra_vars:
            event_type: "{{ event.payload.event }}"
            source: "{{ event.payload.source }}"
            app_name: "{{APP_NAME}}"
            db_host: "{{APP_NAME}}-db"
            api_url: "http://{{APP_NAME}}-app:8080/api"