---
- name: Keycloak Configuration Rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        url_path: /keycloak-config

  rules:
    - name: Configure Keycloak Realm and Client
      condition: event.payload.realm is defined and event.payload.client_id is defined
      action:
        run_playbook:
          name: configure-keycloak.yml
          extra_vars:
            keycloak_url: "{{ event.payload.auth_url }}"
            realm_name: "{{ event.payload.realm }}"
            client_id: "{{ event.payload.client_id }}"
            client_secret: "{{ event.payload.client_secret }}"
            app_name: "{{ app_name | default('{{APP_NAME}}') }}"
            app_port: "{{ app_port | default('{{APP_PORT}}') }}"
            callback_url: "http://{{APP_NAME}}-app:8080/api/keycloak/configured"

    - name: Handle Keycloak Health Check
      condition: event.payload.action == "health_check"
      action:
        run_playbook:
          name: keycloak-health.yml
          extra_vars:
            keycloak_url: "http://{{APP_NAME}}-keycloak:8080"
            callback_url: "http://{{APP_NAME}}-app:8080/api/keycloak/health"

    - name: Create Keycloak User
      condition: event.payload.action == "create_user"
      action:
        run_playbook:
          name: create-keycloak-user.yml
          extra_vars:
            keycloak_url: "http://{{APP_NAME}}-keycloak:8080"
            realm_name: "{{ event.payload.realm }}"
            username: "{{ event.payload.username }}"
            email: "{{ event.payload.email }}"
            first_name: "{{ event.payload.first_name }}"
            last_name: "{{ event.payload.last_name }}"
            temporary_password: "{{ event.payload.temporary_password | default('changeme') }}"